# Generated by Django 5.1.1 on 2024-10-09 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_product_image_product_discount_and_more'),
    ]

    operations = [
         migrations.RunSQL(
            sql='CREATE VIRTUAL TABLE products_product_fts USING fts4(name, description, tags);',
            reverse_sql='DROP TABLE IF EXISTS products_product_fts;'
        ),
    ]
