# Generated by Django 5.1.1 on 2024-10-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20241009_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='review_headline',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
